name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  create:
    tags:
      - v*

env:
  REGISTRY_URL: "ghcr.io"
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_BUILDKIT: "1"

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - run: npm ci
      - run: npm run ci
      - run: npm test
      - run: npm run build
      - uses: nikeee/setup-hurl@v3
      - run: |
          node dist/server.js &
          sleep 2s
          hurl --test tests/classify.hurl

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/holzmaster/nsfwjs

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - uses: docker/build-push-action@v6
        with:
          context: . # https://github.com/docker/build-push-action/issues/182
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
